services:
  - type: web
    name: laravel-app
    branch: master
    dockerfilePath: ./Dockerfile
    buildFilter:
      paths: ["**/*"]
    startCommand: apache2-foreground
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: mysql.railway.internal
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: railway
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: SRVMzaTRdfGGWFoBzCpqjxORMummByuG
